name = "csr-srisathyasai"
compatibility_date = "2026-01-01"
pages_build_output_dir = "."

kv_namespaces = [
  { binding = "CSR_KV", id = "csr_portal_kv_namespace" }
]

[env.production]
name = "csr-srisathyasai-prod"
